# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DUwvp09-Z6Gm_zRI0fh4UPeVhfq8SMKw
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression

def marks_prediction(hrs):

    X = pd.read_csv("tbl_x.csv")
    Y = pd.read_csv("tbl_y.csv")

    X.head()

    Y.head()

    x = X.values

    y = Y.values
    # plt.scatter(x, y)

    # plt.xlabel("marks")
    # plt.ylabel("no_of_hrs")
    # plt.show()


    model = LinearRegression()
    model.fit(x,y)
    
    x_test = np.array(hrs)
    x_test = x_test.reshape((1, -1))

    return model.predict(x_test)[0]
   
   
